# Generated by Django 5.1.15 on 2026-08-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_announcement_order_copies_order_order_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_group_link', models.URLField(blank=True, help_text='WhatsApp group invite link (e.g., https://chat.whatsapp.com/...)', max_length=500)),
                ('support_admin_number', models.CharField(blank=True, help_text='Default admin WhatsApp number if no admin found', max_length=15)),
                ('support_agent_fallback', models.CharField(blank=True, help_text='Fallback agent WhatsApp number if none assigned', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Setting',
                'verbose_name_plural': 'Support Settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('research_proposal', 'Research Proposal'), ('essay', 'Essay/Assignment'), ('report', 'Technical Report'), ('cv_resume', 'CV/Resume'), ('business_plan', 'Business Plan'), ('presentation', 'Presentation Slides'), ('thesis_chapter', 'Thesis Chapter'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='What do you need?')),
                ('instructions', models.TextField(help_text='Specific requirements (formatting, style, references)')),
                ('word_count_target', models.IntegerField(default=1000)),
                ('deadline', models.DateTimeField()),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('notebooklm_link', models.URLField(blank=True, help_text='Link to NotebookLM project')),
                ('research_notes', models.TextField(blank=True, help_text='Extracted notes from NotebookLM')),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('ai_draft_text', models.TextField(blank=True)),
                ('ai_draft_tokens', models.IntegerField(default=0)),
                ('latex_code', models.TextField(blank=True)),
                ('overleaf_project_url', models.URLField(blank=True)),
                ('final_pdf', models.FileField(blank=True, upload_to='final_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('research', 'Research Phase (NotebookLM)'), ('generating', 'AI Generating Draft'), ('formatting', 'Formatting to LaTeX'), ('human_review', 'Team Review'), ('client_review', 'Awaiting Client Review'), ('revision', 'Revisions Requested'), ('approved', 'Final Approval'), ('printing', 'Ready to Print'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('revision_count', models.IntegerField(default=0)),
                ('max_revisions', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doc_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_notes', models.TextField()),
                ('team_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='orders.documentcreationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doc_sources/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='orders.documentcreationrequest')),
            ],
        ),
    ]
